name: CI - Backend Tests

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restaurer les dépendances
        run: dotnet restore Backend.Tests/Backend.Tests.csproj

      - name: Build
        run: dotnet build Backend.Tests/Backend.Tests.csproj --no-restore --configuration Release

      - name: Lancer les tests
        run: dotnet test Backend.Tests/Backend.Tests.csproj --no-build --configuration Release --collect:"XPlat Code Coverage"